[package]
name = "tui_chat_client"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = "0.29.0"
serde = {version="1.0.219", features = ["derive"]}
tokio = { version = "1.45.1", features = ["full"] }
serde_json = "1.0.140"
anyhow = "1.0.98"
crossterm = "0.29.0"
chrono = "0.4.41"
